
# colorless_cards.py

# Uncommon Cards
BANDAGE_UP = "Bandage Up"
BLIND = "Blind"
DARK_SHACKLES = "Dark Shackles"
DEEP_BREATH = "Deep Breath"
DISCOVERY = "Discovery"
DRAMATIC_ENTRANCE = "Dramatic Entrance"
ENLIGHTENMENT = "Enlightenment"
FINESSE = "Finesse"
FLASH_OF_STEEL = "Flash of Steel"
FORETHOUGHT = "Forethought"
GOOD_INSTINCTS = "Good Instincts"
IMPATIENCE = "Impatience"
JACK_OF_ALL_TRADES = "Jack Of All Trades"
MADNESS = "Madness"
MIND_BLAST = "Mind Blast"
PANACEA = "Panacea"
PANIC_BUTTON = "Panic Button"
PURITY = "Purity"
SWIFT_STRIKE = "Swift Strike"
TRIP = "Trip"

# Rare Cards
APOTHEOSIS = "Apotheosis"
CHRYSALIS = "Chrysalis"
HAND_OF_GREED = "Hand of Greed"
MAGNETISM = "Magnetism"
MASTER_OF_STRATEGY = "Master Of Strategy"
MAYHEM = "Mayhem"
METAMORPHOSIS = "Metamorphosis"
PANACHE = "Panache"
SADISTIC_NATURE = "Sadistic Nature"
SECRET_TECHNIQUE = "Secret Technique"
SECRET_WEAPON = "Secret Weapon"
THE_BOMB = "The Bomb"
THINKING_AHEAD = "Thinking Ahead"
TRANSMUTATION = "Transmutation"
VIOLENCE = "Violence"

# Special Cards
APPARITION = "Apparition"
BETA = "Beta"
BITE = "Bite"
EXPUNGER = "Expunger"
INSIGHT = "Insight"
JAX = "J.A.X."
MIRACLE = "Miracle"
OMEGA = "Omega"
RITUAL_DAGGER = "Ritual Dagger"
SAFETY = "Safety"
SHIV = "Shiv"
SMITE = "Smite"
THROUGH_VIOLENCE = "Through Violence"