#Silent_card.py

#Green cards


# Starter Cards
DEFEND_G = "Defend"
NEUTRALIZE = "Neutralize"
STRIKE_G = "Strike"
SURVIVOR = "Survivor"

# Common Cards
ACROBATICS = "Acrobatics"
BACKFLIP = "Backflip"
BANE = "Bane"
BLADE_DANCE = "Blade Dance"
CLOAK_AND_DAGGER = "Cloak and Dagger"
DAGGER_SPRAY = "Dagger Spray"
DAGGER_THROW = "Dagger Throw"
DEADLY_POISON = "Deadly Poison"
DEFLECT = "Deflect"
DODGE_AND_ROLL = "Dodge and Roll"
FLYING_KNEE = "Flying Knee"
OUTMANEUVER = "Outmaneuver"
PIERCING_WAIL = "Piercing Wail"
POISONED_STAB = "Poisoned Stab"
PREPARED = "Prepared"
QUICK_SLASH = "Quick Slash"
SLICE = "Slice"
SNEAKY_STRIKE = "Sneaky Strike"
SUCKER_PUNCH = "Sucker Punch"

# Uncommon Cards
ACCURACY = "Accuracy"
ALL_OUT_ATTACK = "All-Out Attack"
BACKSTAB = "Backstab"
BLUR = "Blur"
BOUNCING_FLASK = "Bouncing Flask"
CALCULATED_GAMBLE = "Calculated Gamble"
CALTROPS = "Caltrops"
CATALYST = "Catalyst"
CHOKE = "Choke"
CONCENTRATE = "Concentrate"
CRIPPLING_CLOUD = "Crippling Cloud"
DASH = "Dash"
DISTRACTION = "Distraction"
ENDLESS_AGONY = "Endless Agony"
ESCAPE_PLAN = "Escape Plan"
EVISCERATE = "Eviscerate"
EXPERTISE = "Expertise"
FINISHER = "Finisher"
FLECHETTES = "Flechettes"
FOOTWORK = "Footwork"
HEEL_HOOK = "Heel Hook"
INFINITE_BLADES = "Infinite Blades"
LEG_SWEEP = "Leg Sweep"
MASTERFUL_STAB = "Masterful Stab"
NOXIOUS_FUMES = "Noxious Fumes"
PREDATOR = "Predator"
REFLEX = "Reflex"
RIDDLE_WITH_HOLES = "Riddle With Holes"
SETUP = "Setup"
SKEWER = "Skewer"
TACTICIAN = "Tactician"
TERROR = "Terror"
WELL_LAID_PLANS = "Well-Laid Plans"

# Rare Cards
A_THOUSAND_CUTS = "A Thousand Cuts"
ADRENALINE = "Adrenaline"
AFTER_IMAGE = "After Image"
ALCHEMIZE = "Alchemize"
BULLET_TIME = "Bullet Time"
BURST = "Burst"
CORPSE_EXPLOSION = "Corpse Explosion"
DIE_DIE_DIE = "Die Die Die"
DOPPELGANGER = "Doppelganger"
ENVENOM = "Envenom"
GLASS_KNIFE = "Glass Knife"
GRAND_FINALE = "Grand Finale"
MALAISE = "Malaise"
NIGHTMARE = "Nightmare"
PHANTASMAL_KILLER = "Phantasmal Killer"
STORM_OF_STEEL = "Storm of Steel"
TOOLS_OF_THE_TRADE = "Tools of the Trade"
UNLOAD = "Unload"
WRAITH_FORM = "Wraith Form"