# watcher_cards.py

# Starter Cards
DEFEND_W = "Defend"
ERUPTION = "Eruption"
STRIKE_W = "Strike"
VIGILANCE = "Vigilance"

# Common Cards
BOWLING_BASH = "Bowling Bash"
CONSECRATE = "Consecrate"
CRESCENDO = "Crescendo"
CRUSH_JOINTS = "Crush Joints"
CUT_THROUGH_FATE = "Cut Through Fate"
EMPTY_BODY = "Empty Body"
EMPTY_FIST = "Empty Fist"
EVALUATE = "Evaluate"
FLURRY_OF_BLOWS = "Flurry of Blows"
FLYING_SLEEVES = "Flying Sleeves"
FOLLOW_UP = "Follow-Up"
HALT = "Halt"
JUST_LUCKY = "Just Lucky"
PRESSURE_POINTS = "Pressure Points"
PROSTRATE = "Prostrate"
PROTECT = "Protect"
SASH_WHIP = "Sash Whip"
THIRD_EYE = "Third Eye"
TRANQUILITY = "Tranquility"

# Uncommon Cards
BATTLE_HYMN = "Battle Hymn"
CARVE_REALITY = "Carve Reality"
COLLECT = "Collect"
CONCLUDE = "Conclude"
DECEIVE_REALITY = "Deceive Reality"
EMPTY_MIND = "Empty Mind"
FASTING = "Fasting"
FEAR_NO_EVIL = "Fear No Evil"
FOREIGN_INFLUENCE = "Foreign Influence"
FORESIGHT = "Foresight"
INDIGNATION = "Indignation"
INNER_PEACE = "Inner Peace"
LIKE_WATER = "Like Water"
MEDITATE = "Meditate"
MENTAL_FORTRESS = "Mental Fortress"
NIRVANA = "Nirvana"
PERSEVERANCE = "Perseverance"
PRAY = "Pray"
REACH_HEAVEN = "Reach Heaven"
RUSHDOWN = "Rushdown"
SANCTITY = "Sanctity"
SANDS_OF_TIME = "Sands of Time"
SIGNATURE_MOVE = "Signature Move"
SIMMERING_FURY = "Simmering Fury"
STUDY = "Study"
SWIVEL = "Swivel"
TALK_TO_THE_HAND = "Talk to the Hand"
TANTRUM = "Tantrum"
WALLOP = "Wallop"
WAVE_OF_THE_HAND = "Wave of the Hand"
WEAVE = "Weave"
WHEEL_KICK = "Wheel Kick"
WINDMILL_STRIKE = "Windmill Strike"
WORSHIP = "Worship"
WREATH_OF_FLAME = "Wreath of Flame"

# Rare Cards
ALPHA = "Alpha"
BLASPHEMY = "Blasphemy"
BRILLIANCE = "Brilliance"
CONJURE_BLADE = "Conjure Blade"
DEUS_EX_MACHINA = "Deus Ex Machina"
DEVA_FORM = "Deva Form"
DEVOTION = "Devotion"
ESTABLISHMENT = "Establishment"
JUDGMENT = "Judgment"
LESSON_LEARNED = "Lesson Learned"
MASTER_REALITY = "Master Reality"
OMNISCIENCE = "Omniscience"
RAGNAROK = "Ragnarok"
SCRAWL = "Scrawl"
SPIRIT_SHIELD = "Spirit Shield"
VAULT = "Vault"
WISH = "Wish"